spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhaLC/SpringCloudConfig.git
          search-paths: /SpringCloudConfig
          username:
          password:
        config:
          label: develop

server:
  port: 8982



